In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
import numpy as np

In [9]:
data = pd.read_csv("Iris.csv")

print(data.head())
data = data.dropna()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            NaN           0.2  Iris-setosa


In [10]:
X = data.iloc[:, :-1]   # all columns except last
y = data.iloc[:, -1]    # last column (species)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [23]:
print(X_test)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
74    75            6.4           2.9            4.3           1.3
19    20            5.1           3.8            1.5           0.3
118  119            7.7           2.6            6.9           2.3
79    80            5.7           2.6            3.5           1.0
77    78            6.7           3.0            5.0           1.7
32    33            5.2           4.1            1.5           0.1
65    66            6.7           3.1            4.4           1.4
141  142            6.9           3.1            5.1           2.3
69    70            5.6           2.5            3.9           1.1
83    84            6.0           2.7            5.1           1.6
110  111            6.5           3.2            5.1           2.0
13    14            4.3           3.0            1.1           0.1
37    38            4.9           3.1            1.5           0.1
10    11            5.4           3.7            1.5          

In [12]:
model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [13]:
y_pred = model.predict(X_test)

print("Predicted Values:")
print(y_pred)

Predicted Values:
['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa']


In [14]:
'''
Class 0 → Setosa

Class 1 → Versicolor

Class 2 → Virginica
'''
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]


In [20]:
cm = np.array(cm)

n = cm.shape[0]

for i in range(n):

    TP = cm[i][i]
    FP = sum(cm[:, i]) - TP
    FN = sum(cm[i, :]) - TP
    TN = cm.sum() - (TP + FP + FN)

    print("Class", i)
    print("TP:", TP)
    print("FP:", FP)
    print("FN:", FN)
    print("TN:", TN)
    print()

Class 0
TP: 19
FP: 0
FN: 0
TN: 26

Class 1
TP: 13
FP: 1
FN: 0
TN: 31

Class 2
TP: 12
FP: 0
FN: 1
TN: 32



In [21]:
#When a confusion matrix is multi-class (3×3), we compute TP, FP, TN, FN for each class using one-vs-all method.

for i in range(n):

    TP = cm[i][i]
    FP = sum(cm[:, i]) - TP
    FN = sum(cm[i, :]) - TP
    TN = cm.sum() - (TP + FP + FN)

    accuracy = (TP + TN) / cm.sum()
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    error_rate = (FP + FN) / cm.sum()

    print("Class", i)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("Error Rate:", error_rate)
    print()

Class 0
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
Error Rate: 0.0

Class 1
Accuracy: 0.9777777777777777
Precision: 0.9285714285714286
Recall: 1.0
Error Rate: 0.022222222222222223

Class 2
Accuracy: 0.9777777777777777
Precision: 1.0
Recall: 0.9230769230769231
Error Rate: 0.022222222222222223



In [26]:
new_samples = pd.DataFrame(
    [
        [1, 5.1,3.5,1.4,0.2],
        [2, 6.0,2.9,4.5,1.5],
        [3, 6.5,3.0,4.8,1.8]
    ],
    columns=X.columns
)

predictions = model.predict(new_samples)

print("Predictions:", predictions)

Predictions: ['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor']
